ALTER TABLE news ADD COLUMN title_hash   TEXT;
ALTER TABLE news ADD COLUMN ai_verified  INTEGER DEFAULT 0;
ALTER TABLE news ADD COLUMN ai_reasoning TEXT;
ALTER TABLE news ADD COLUMN is_fake_flag INTEGER DEFAULT 0;
