from pathlib import Path

BASE_DIR = Path(__file__).parent.parent
DB_PATH = BASE_DIR / "data" / "esg_news.db"

BANK_QUERIES = {
    "itau": [
        "Itaú ESG", "Itaú sustentabilidade", "Itaú BBA sustentabilidade",
        "Itaú verde", "Itaú net zero", "Itaú Unibanco ESG",
        "Itaú título verde", "Itaú diversidade racial", "Itaú inclusão financeira",
        "Itaú crédito de carbono",
    ],
    "bradesco": [
        "Bradesco ESG", "Bradesco sustentabilidade", "Bradesco social",
        "Bradesco verde", "Bradesco Next ESG",
        "Bradesco título verde", "Bradesco diversidade", "Bradesco inclusão financeira",
        "Bradesco descarbonização",
    ],
    "santander": [
        "Santander ESG", "Santander títulos verdes",
        "Santander sustentável", "Santander sustentabilidade",
        "Santander diversidade", "Santander financiamento verde",
        "Santander inclusão financeira", "Santander agro sustentável",
    ],
    "bb": [
        "Banco do Brasil ESG", "BB sustentabilidade",
        "Banco do Brasil verde", "Banco do Brasil ambiental",
        "Banco do Brasil Pronaf", "Banco do Brasil agro sustentável",
        "Banco do Brasil diversidade", "BB título verde",
    ],
    "caixa": [
        "Caixa ESG", "Caixa sustentabilidade",
        "Caixa habitação social", "Caixa verde",
        "Caixa Minha Casa Minha Vida", "Caixa crédito habitacional social",
        "Caixa inclusão financeira",
    ],
    "btg": [
        "BTG ESG", "BTG Pactual sustentabilidade",
        "BTG verde", "BTG Pactual ambiental",
        "BTG Pactual diversidade", "BTG título verde",
        "BTG crédito de carbono",
    ],
    "nubank": [
        "Nubank ESG", "Nubank sustentabilidade",
        "Nubank social", "Nubank impacto",
        "Nubank diversidade", "Nubank inclusão financeira",
        "Nubank relatório ESG",
    ],
    "safra": [
        "Banco Safra ESG", "Banco Safra sustentabilidade",
        "Banco Safra verde", "Banco Safra ambiental",
        "Banco Safra social", "Banco Safra diversidade",
        "Banco Safra título verde",
    ],
    "xp": [
        "XP Inc ESG", "XP Inc sustentabilidade",
        "XP Investimentos governança", "XP Investimentos diversidade",
        "XP Inc diversidade", "XP Inc relatório ESG",
        "XP Inc inclusão financeira",
    ],
    "inter": [
        "Banco Inter ESG", "Inter sustentabilidade",
        "Inter social", "Inter verde",
        "Banco Inter diversidade", "Banco Inter inclusão financeira",
        "Banco Inter relatório ESG",
    ],
    "c6": [
        "C6 Bank ESG", "C6 Bank sustentabilidade",
        "C6 Bank social", "C6 Bank verde",
        "C6 Bank diversidade", "C6 Bank inclusão financeira",
        "C6 Bank neutralidade carbono",
    ],
    "sicoob": [
        "Sicoob ESG", "Sicoob sustentabilidade",
        "Sicoob social", "Sicoob cooperativa verde",
        "Sicoob Pronaf", "Sicoob agro sustentável",
        "Sicoob inclusão financeira",
    ],
    "bnb": [
        "Banco do Nordeste ESG", "Banco do Nordeste sustentabilidade",
        "Banco do Nordeste social", "BNB verde", "BNB ambiental",
        "Banco do Nordeste meio ambiente",
        "Banco do Nordeste FNE Verde", "Banco do Nordeste semiárido",
        "Banco do Nordeste microcrédito",
    ],
    "brb": [
        "BRB ESG", "BRB sustentabilidade", "Banco de Brasília ESG",
        "BRB verde", "BRB social",
        "BRB diversidade", "BRB inclusão financeira",
    ],
    "original": [
        "Banco Original ESG", "Banco Original sustentabilidade",
        "Banco Original verde", "Banco Original social",
        "Banco Original diversidade", "Banco Original agro sustentável",
    ],
    "pan": [
        "Banco Pan ESG", "Banco Pan sustentabilidade",
        "Banco Pan social", "Banco Pan inclusão financeira",
        "Banco Pan diversidade", "Banco Pan microcrédito",
    ],
    "bmg": [
        "Banco BMG ESG", "Banco BMG sustentabilidade",
        "Banco BMG social", "BMG inclusão",
        "Banco BMG diversidade", "Banco BMG verde",
    ],
    "agibank": [
        "Agibank ESG", "Agibank sustentabilidade",
        "Agibank social", "Agibank inclusão financeira",
        "Agibank diversidade", "Agibank microcrédito",
    ],
    "picpay": [
        "PicPay Bank ESG", "PicPay sustentabilidade",
        "PicPay social", "PicPay impacto", "PicPay inclusão",
        "PicPay diversidade", "PicPay inclusão financeira",
    ],
    "bs2": [
        "Banco BS2 ESG", "BS2 sustentabilidade",
        "BS2 social", "BS2 verde",
        "BS2 diversidade", "BS2 título verde",
    ],
    "bv": [
        "Banco BV ESG", "Banco BV sustentabilidade",
        "Banco Votorantim ESG", "BV financiamentos verdes",
        "Banco BV verde", "Banco BV social",
        "Banco BV diversidade", "Banco BV veículo elétrico",
        "Banco BV energia solar",
    ],
}

ESG_KEYWORDS = {
    "E": [
        "carbono", "carbon", "emissão", "emissões", "clima", "climate",
        "verde", "green bond", "green bonds", "sustentável", "sustainable",
        "ambiental", "environmental", "energia renovável", "renewable energy",
        "solar", "eólica", "wind", "floresta", "forest", "desmatamento",
        "deforestation", "biodiversidade", "biodiversity", "títulos verdes",
        "crédito verde", "financiamento verde", "pegada", "footprint",
        "reciclagem", "recycling", "água", "water", "aquecimento global",
        "net zero", "neutralidade de carbono", "descarbonização", "ESG ambiental",
        "emissão zero", "zero emissão", "crédito de carbono", "compensação carbono",
    ],
    "S": [
        "social", "inclusão", "inclusion", "diversidade", "diversity",
        "gênero", "gender", "mulher", "women", "racial", "etnia", "ethnicity",
        "comunidade", "community", "habitação", "housing", "moradia",
        "educação", "education", "saúde", "health", "trabalho", "emprego",
        "microcrédito", "microcredit", "inclusão financeira", "financial inclusion",
        "vulnerável", "vulnerable", "pobreza", "poverty", "desigualdade",
        "direitos humanos", "human rights", "trabalhador", "worker",
        "liderança feminina", "conselho diverso", "equidade", "equity",
        "refugiado", "acessibilidade", "accessibility", "comunidades",
    ],
    "G": [
        "governança", "governance", "transparência", "transparency",
        "conselho", "board", "diretoria", "compliance", "ética", "ethics",
        "anticorrupção", "anti-corruption", "regulatório", "regulatory",
        "risco", "risk", "auditoria", "audit", "relatório anual", "annual report",
        "política", "policy", "código de conduta", "code of conduct",
        "remuneração executiva", "executive pay", "acionista", "shareholder",
        "LGPD", "privacidade", "privacy", "dados", "data protection",
        "integridade", "integrity", "ESG relatório", "divulgação", "disclosure",
    ],
}

# Terms used to detect bank mentions in article text (for multi-bank badge)
BANK_MENTION_TERMS = {
    "itau":      ["itaú", "itau", "itaúbba", "itaubba"],
    "bradesco":  ["bradesco"],
    "santander": ["santander"],
    "bb":        ["banco do brasil", "bb investimentos"],
    "caixa":     ["caixa econômica", "caixa economica", "cef"],
    "btg":       ["btg pactual", "btg"],
    "nubank":    ["nubank", "nu holdings"],
    "safra":     ["banco safra", "safra bank"],
    "xp":        ["xp investimentos", "xp inc"],
    "inter":     ["banco inter", "inter bank"],
    "c6":        ["c6 bank", "c6bank"],
    "sicoob":    ["sicoob"],
    "bnb":       ["banco do nordeste", "bnb"],
    "brb":       ["brb", "banco de brasília", "banco de brasilia"],
    "original":  ["banco original"],
    "pan":       ["banco pan", "pan financeira"],
    "bmg":       ["banco bmg", "bmg"],
    "agibank":   ["agibank"],
    "picpay":    ["picpay bank", "picpay"],
    "bs2":       ["banco bs2", "bs2"],
    "bv":        ["banco bv", "banco votorantim", "bv financeira"],
}

BANK_DISPLAY_NAMES = {
    "itau":      "Itaú",
    "bradesco":  "Bradesco",
    "santander": "Santander",
    "bb":        "Banco do Brasil",
    "caixa":     "Caixa",
    "btg":       "BTG Pactual",
    "nubank":    "Nubank",
    "safra":     "Safra",
    "xp":        "XP Investimentos",
    "inter":     "Inter",
    "c6":        "C6 Bank",
    "sicoob":    "Sicoob",
    "bnb":       "Banco do Nordeste",
    "brb":       "BRB",
    "original":  "Banco Original",
    "pan":       "Banco Pan",
    "bmg":       "Banco BMG",
    "agibank":   "Agibank",
    "picpay":    "PicPay Bank",
    "bs2":       "Banco BS2",
    "bv":        "Banco BV",
}

# Official brand colors (primary color for card border)
BANK_COLORS = {
    "itau":      "#EC7000",
    "bradesco":  "#CC092F",
    "santander": "#EC0000",
    "bb":        "#D4A017",
    "caixa":     "#005CA9",
    "btg":       "#1A1A2E",
    "nubank":    "#820AD1",
    "safra":     "#003B5C",
    "xp":        "#000000",
    "inter":     "#FF7A00",
    "c6":        "#242424",
    "sicoob":    "#007A3D",
    "bnb":       "#007B40",
    "brb":       "#005B9A",
    "original":  "#00884A",
    "pan":       "#FF4B00",
    "bmg":       "#E30613",
    "agibank":   "#FF6B00",
    "picpay":    "#21C25E",
    "bs2":       "#0050A0",
    "bv":        "#005BAA",
}

# Lightened brand colors for card backgrounds
BANK_COLORS_LIGHT = {
    "itau":      "#FDE8D0",
    "bradesco":  "#FAD0D7",
    "santander": "#FAD0D0",
    "bb":        "#FEF5CC",
    "caixa":     "#CCE2F4",
    "btg":       "#D0D0DC",
    "nubank":    "#EDD5FA",
    "safra":     "#CCDAE3",
    "xp":        "#DEDEDE",
    "inter":     "#FFE4CC",
    "c6":        "#D8D8D8",
    "sicoob":    "#CCE8D9",
    "bnb":       "#CCE8D8",
    "brb":       "#CCE0F0",
    "original":  "#CCE8D8",
    "pan":       "#FFE0CC",
    "bmg":       "#FAD0D0",
    "agibank":   "#FFE4CC",
    "picpay":    "#D0F5E0",
    "bs2":       "#CCE0F5",
    "bv":        "#CCE0F5",
}

# Iniciais dos bancos para o badge SVG inline (não depende de URL externa)
BANK_INITIALS = {
    "itau":      "IT",
    "bradesco":  "BR",
    "santander": "SA",
    "bb":        "BB",
    "caixa":     "CX",
    "btg":       "BT",
    "nubank":    "NU",
    "safra":     "SF",
    "xp":        "XP",
    "inter":     "IN",
    "c6":        "C6",
    "sicoob":    "SC",
    "bnb":       "BN",
    "brb":       "BR",
    "original":  "OR",
    "pan":       "PN",
    "bmg":       "BG",
    "agibank":   "AG",
    "picpay":    "PP",
    "bs2":       "B2",
    "bv":        "BV",
}

# Whitelist fechada — jornais renomados, reguladores, entidades do setor e canais
# oficiais dos bancos. Qualquer domínio fora desta lista é rejeitado.
TRUSTED_DOMAINS = {
    # --- Jornais e revistas financeiras ---
    "valoreconomico.com.br",
    "valor.globo.com",
    "estadao.com.br",
    "einvestidor.estadao.com.br",
    "folha.uol.com.br",
    "estudio.folha.uol.com.br",
    "exame.com",
    "infomoney.com.br",
    "moneytimes.com.br",
    "istoedinheiro.com.br",
    "neofeed.com.br",
    "braziljournal.com",
    "capital.com.br",
    "dci.com.br",
    "seudinheiro.com",
    "suno.com.br",
    # --- Agências de notícias internacionais ---
    "bloomberg.com",
    "bloomberg.com.br",
    "reuters.com",
    "ft.com",
    # --- TV e portais jornalísticos ---
    "cnnbrasil.com.br",
    "g1.globo.com",
    "agenciabrasil.ebc.com.br",
    "band.uol.com.br",
    "jovempan.news",
    # --- Reguladores e órgãos governamentais ---
    "bcb.gov.br",
    "cvm.gov.br",
    "fazenda.gov.br",
    "mma.gov.br",
    "planalto.gov.br",
    "senado.leg.br",
    "agencia.senado.leg.br",
    "camara.leg.br",
    # --- Entidades do setor financeiro e ESG ---
    "febraban.org.br",
    "b3.com.br",
    "anbima.com.br",
    "abrapp.org.br",
    "abbc.org.br",
    "amecbrasil.org.br",
    "gri-standards.org",
    "cdp.net",
    "unpri.org",
    "sbfin.org.br",
    "terraotb.org.br",
    # --- Canais oficiais dos bancos e subsidiárias ---
    "itau.com.br",
    "ri.itau.com.br",
    "itaubba.com",
    "bradesco.com.br",
    "ri.bradesco.com.br",
    "next.me",
    "santander.com.br",
    "bb.com.br",
    "agencia.bb.com.br",
    "caixa.gov.br",
    "btgpactual.com",
    "nubank.com.br",
    "international.nubank.com.br",
    "safra.com.br",
    "oespecialista.safra.com.br",
    "xpi.com.br",
    "conteudos.xpi.com.br",
    "bancointer.com.br",
    "c6bank.com.br",
    "sicoob.com.br",
    "bnb.gov.br",
    "brb.com.br",
    "original.com.br",
    "bancopan.com.br",
    "bancobmg.com.br",
    "agibank.com.br",
    "picpay.com",
    "bs2.com.br",
    "bv.com.br",
}

ESG_LABELS = {
    "E": "Ambiental",
    "S": "Social",
    "G": "Governança",
    "unknown": "Não classificado",
}

ESG_COLORS = {
    "E": "#2d6a4f",
    "S": "#1d3557",
    "G": "#6a0572",
    "unknown": "#6c757d",
}

ESG_COLORS_LIGHT = {
    "E": "#b7e4c7",
    "S": "#a8dadc",
    "G": "#e2b0ff",
    "unknown": "#dee2e6",
}

ESG_EMOJIS = {
    "E": "🌱",
    "S": "🤝",
    "G": "⚖️",
    "unknown": "📰",
}
